spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 0113
    url: jdbc:postgresql://localhost:5432/postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  version: '@springdoc.version@'
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger
    tagsSorter: alpha
    use-root-path: true
  cache:
    disabled: true