spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 0113
    url: jdbc:postgresql://localhost:5432/postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true


springdoc:
  version: '@springdoc.version@'
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    tagsSorter: alpha
    use-root-path: true
  cache:
    disabled: true